[character]
success_symbol = "[󰘧](#2fafff)"
error_symbol = "[󰘧](#ff5f59)"
vimcmd_symbol = "[󰘧](#2fafff)"
vimcmd_replace_one_symbol = "[󰘧](#b6a0ff)"
vimcmd_replace_symbol = "[󰘧](#b6a0ff)"
vimcmd_visual_symbol = "[󰘧](#d0bc00)"

[git_status]
disabled = true

[package]
disabled = true

